### ISSUE TITLE
`bpmn-server` version compatibility with `bpmn-web`

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [bpmnServer/bpmn-web#13]
Hi @ralphhanna

NOT exactly an issue but more of a clarification.

I suppose, `bpmn-web` would only be compatible with the latest version of `bpmn-server`. I see a lot of [minor versions for 2.0.X](https://www.npmjs.com/package/bpmn-server?activeTab=versions) of `bpmn-server` in npm.

Is [2.0.6-alpha2](https://www.npmjs.com/package/bpmn-server/v/2.0.6-alpha2) stable to use with `bpmn-web` v2.1.0?

Thanks.

**Comment by ralphhanna** [comment]
Yes stable but subject to minor changes
Also compatible with bpmn-client
