### ISSUE TITLE
Errors in the script `src/routes/api2.ts`

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [bpmnServer/bpmn-web#14]
Hi @ralphhanna

Mya be you are already aware but just pointing to the build issues.

![image](https://github.com/bpmnServer/bpmn-web/assets/55505611/15bcda1c-8793-4043-8f9f-f5b39375ec52)

I could have a raised PR correcting these but wasn't sure whether you are in the midst of changing anything major with the restructuring and all. So, I'll let you complete them.

Is it possible to give any timeline from which `bpmn-web` would be ready as in there won't be any major restructuring or changes?

Thank you for all your work.

**Comment by ralphhanna** [comment]
sorry, fixed.
This release should be Ok, no major changes planned, only minor bug fixes with the UI and better docs

Thanks

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna

It seems you have updated `bpmn-server` to another version and now, this requires `query` parameter in the `api.model.list`

![image](https://github.com/bpmnServer/bpmn-web/assets/55505611/037433ab-084f-48c9-8e06-9d7868dc92d1)

**Comment by ralphhanna** [comment]
Was fixed, but forgot to update issue status
