### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [bpmnServer/bpmn-web#17]
Hi @ralphhanna 

`npm run build` results in error due to the [`path-scurry` dependency in `glob`](https://github.com/isaacs/node-glob/issues/537).
Could you please update the dependencies? Thank you.

**Comment by ralphhanna** [comment]
Hi @MaheshkumarSundaram 
I think this issue was already corrected by glob.

![image](https://github.com/bpmnServer/bpmn-web/assets/11893416/15161a11-9e86-4cfd-8791-f79b2db48e96)

**Comment by ralphhanna** [comment]
I am going ahead and close this one
