### ISSUE TITLE
keep .ts in src

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-web#6]
Hi
Previously the .ts and .js stored in `./src` folder, I think your intension is transfer `.js` staff into `./dist`. However the `.ts` also been moved to `./dist`. 
It is not major defect but weird. The .ts may keep in src and build file in ./dist. While we wish to trace source code from `node_modules` it is clearer

**Comment by linonetwo** [comment]
I try the latest main branch, seems this is fixed.

**Comment by linonetwo** [comment]
![图片](https://github.com/bpmnServer/bpmn-web/assets/3746270/ba0510cc-ce5e-40f5-877c-7dfe3b6ecd1e)

**Comment by ralphhanna** [comment]
I have included src in the npm package
![image](https://github.com/bpmnServer/bpmn-web/assets/11893416/91d4e36f-5406-4c66-8ec3-d79a357bdc4c)
